image: "ubuntu"

before_script:
  - apt-get update -qq && apt-get install -y -qq make curl libxml2-utils xsltproc

stages:
  - build
  - test

build:
  stage: build
  script:
    - make
test:
  stage: test
  script:
    - make test

